/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FocusAreasRouteImport } from './routes/focus-areas'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusAreasRoute = FocusAreasRouteImport.update({
  id: '/focus-areas',
  path: '/focus-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/focus-areas': typeof FocusAreasRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mission': typeof MissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/focus-areas': typeof FocusAreasRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mission': typeof MissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/focus-areas': typeof FocusAreasRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mission': typeof MissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/focus-areas'
    | '/get-involved'
    | '/mission'
    | '/sitemap.xml'
    | '/stakeholders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/focus-areas'
    | '/get-involved'
    | '/mission'
    | '/sitemap.xml'
    | '/stakeholders'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/focus-areas'
    | '/get-involved'
    | '/mission'
    | '/sitemap.xml'
    | '/stakeholders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FocusAreasRoute: typeof FocusAreasRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MissionRoute: typeof MissionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StakeholdersRoute: typeof StakeholdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-areas': {
      id: '/focus-areas'
      path: '/focus-areas'
      fullPath: '/focus-areas'
      preLoaderRoute: typeof FocusAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FocusAreasRoute: FocusAreasRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MissionRoute: MissionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StakeholdersRoute: StakeholdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
